version: '3'
services:
  music-catalog-ms:
    image: lbracun/music-catalog-ms:1.0-0
    network_mode: host
    environment:
      PORT: 3000
      TYPEORM_HOST: localhost
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: postgres
      TYPEORM_DATABASE: music_catalog
      TYPEORM_PORT: 5432
      TYPEORM_LOGGING: error,schema
      TYPEORM_CONNECTION: postgres
      TYPEORM_SYNCHRONIZE: 'true'
      TYPEORM_MIGRATIONS_DIR: migrations
      TYPEORM_ENTITIES: dist/**/*.entity.js
      TYPEORM_MIGRATIONS: dist/migrations/**/*.js
    ports:
      - 3000:3000
